
# Add labels the plugin from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - Image segmentation
  - Cell segmentation
  - Object detection
  - Model-based segmentation
  - Deep learning
  - Convolutional neural network
  - Supervised learning
  - Microscopy
  - Medical imaging
  - 2D image
  - 3D image
  - Image time series
  - Multi-channel image
